### ISSUE TITLE
Remove `.PHONY` from `${GOPATH}/bin/go-junit-report` target

### ISSUE THREAD

**Issue by ppxl** [cloudogu/makefiles#34]
Inside file: `test-common.mk`

The current target directive will run every time. When built inside a container where the update is not possible because of FS/UID restrictions this will lead to an error, thus breaking the built when it actually could run

**Comment by ppxl** [comment]
Note: What happens when the pre/post goals are empty? These should be formulated in a way that they run well nonetheless

**Comment by jgizycki** [comment]
pre/post goals for integration testing are clear. The pre/post goals for unit testing look rather concering on the other hand. They are empty and tests verified that the default target is called. I'll investigate.
