### ISSUE TITLE
postinst-Script is not included in debian package

### ISSUE THREAD

**Issue by robertauer** [cloudogu/makefiles#4]
If a postinst-Script is put into the deb/DEBIAN folder, it will not be included in the .deb-package built by the package-debian.mk makefile.
This can be fixed by adding the line
```
@install -m 0755 deb/DEBIAN/postinst $(DEBIAN_TARGET_DIR)/control/postinst
```
to the $(DEBIAN_PACKAGE) build target.

Additionally, keep in mind, that there are similar scripts to postinst such as preinst, postrm etc. See https://wiki.debian.org/MaintainerScripts

**Comment by ppxl** [comment]
Fixed with release v1.0.1 and PR #12
